basePath: /
definitions:
  app.loginReq:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  app.loginResp:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      token_type:
        type: string
    type: object
  app.registerReq:
    properties:
      name:
        type: string
      pass:
        type: string
    type: object
  app.registerResp:
    properties:
      ok:
        type: boolean
    type: object
  ds.ChangeEnrollmentStatusRequestBody:
    properties:
      id:
        type: integer
      status:
        type: string
    type: object
  ds.Course:
    properties:
      capacity:
        type: integer
      coachEmail:
        type: string
      coachName:
        type: string
      coachPhone:
        type: string
      description:
        type: string
      enrolled:
        type: integer
      id:
        type: integer
      image:
        type: string
      location:
        type: string
      status:
        type: string
      title:
        type: string
    type: object
  ds.DeleteEnrollmentToCourseRequestBody:
    properties:
      courseID:
        type: integer
      enrollmentID:
        type: integer
    type: object
  ds.EnrollCourseRequestBody:
    properties:
      courseName:
        type: string
      endDate:
        type: string
      startDate:
        type: string
    type: object
  ds.Enrollment:
    properties:
      dateCreated:
        type: string
      dateFinished:
        type: string
      dateProcessed:
        type: string
      endDate:
        type: string
      id:
        type: integer
      moderator:
        $ref: '#/definitions/ds.User'
      moderatorRefer:
        type: string
      startDate:
        type: string
      status:
        type: string
      user:
        $ref: '#/definitions/ds.User'
      userRefer:
        type: string
    type: object
  ds.User:
    properties:
      name:
        type: string
      pass:
        type: string
      role:
        $ref: '#/definitions/role.Role'
      uuid:
        type: string
    type: object
  role.Role:
    enum:
    - 0
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - Undefined
    - User
    - Moderator
    - Admin
host: 127.0.0.1:8080
info:
  contact: {}
  title: Запись на спортивные курсы МГТУ им. Н. Э. Баумана
  version: 0.0-0
paths:
  /course/{course}:
    get:
      description: Возвращает данные курса с переданным названием
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Получить курс
      tags:
      - Курсы
  /course/add:
    put:
      consumes:
      - application/json
      description: Создает новый курс с параметрами, описанными в json'е
      parameters:
      - description: Характеристики нового курса
        in: body
        name: course
        required: true
        schema:
          $ref: '#/definitions/ds.Course'
      produces:
      - application/json
      responses:
        "201":
          description: Курс успешно добавлен
          schema:
            type: string
      summary: Добавляет новый курс в БД
      tags:
      - Курсы
  /course/delete/{course_title}:
    put:
      consumes:
      - application/json
      description: Находит курс по его названию и изменяет его статус на "Недоступен"
      parameters:
      - description: Название курса
        in: path
        name: course_title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Found
          schema:
            type: string
      summary: Удалить курс
      tags:
      - Курсы
  /course/delete_restore/{course_title}:
    get:
      description: Изменяет статус курса с "Действует" на "Недоступен" и обратно
      parameters:
      - description: Название курса
        in: path
        name: course_title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Удалить или восстановить курс
      tags:
      - Курсы
  /course/edit:
    put:
      consumes:
      - application/json
      description: Находит курс по имени и обновляет перечисленные поля
      parameters:
      - description: Данные редактируемого курса (должны содержать имя курса или его
          id)
        in: body
        name: course
        required: true
        schema:
          $ref: '#/definitions/ds.Course'
      produces:
      - application/json
      responses:
        "302":
          description: Found
          schema:
            type: string
      summary: Редактировать курс
      tags:
      - Курсы
  /courses:
    get:
      consumes:
      - application/json
      description: Возвращает все существующие курсы
      parameters:
      - description: Паттерн названия курса
        in: query
        name: name_pattern
        type: string
      - description: Локация
        in: query
        name: location
        type: string
      - description: Статус курса (Действует/Недействителен)
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Получить все существующие курсы
      tags:
      - Курсы
  /enroll:
    put:
      consumes:
      - application/json
      description: Создаёт новую заявку и связывает её с курсом
      parameters:
      - description: Параметры записи
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/ds.EnrollCourseRequestBody'
      produces:
      - application/json
      responses:
        "302":
          description: Found
          schema:
            type: string
      summary: Записать на курс
      tags:
      - Запись
  /enrollment:
    get:
      consumes:
      - application/json
      description: Возвращает запись с переданными параметрами
      parameters:
      - description: Статус записи
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Found
          schema:
            type: string
      summary: Получить запись
      tags:
      - Записи
  /enrollment/delete/{enrollment_id}:
    put:
      consumes:
      - application/json
      description: Изменяет статус записи на "Удалён"
      parameters:
      - description: id записи
        in: path
        name: enrollment_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "302":
          description: Found
          schema:
            type: string
      summary: Удалить запись
      tags:
      - Записи
  /enrollment/edit:
    put:
      consumes:
      - application/json
      description: Находит запись и редактирует её поля
      parameters:
      - description: Запись
        in: body
        name: enrollment
        schema:
          $ref: '#/definitions/ds.Enrollment'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
      summary: Редактировать запись
      tags:
      - Записи
  /enrollment/status_change:
    put:
      consumes:
      - application/json
      description: Получает id заявки и новый статус и производит необходимые обновления
      parameters:
      - description: Request body
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/ds.ChangeEnrollmentStatusRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
      summary: Редактировать статус записи
      tags:
      - Запись
  /enrollment_to_course/delete:
    put:
      consumes:
      - application/json
      description: Удаляет запись в таблице enrollment_to_course
      parameters:
      - description: Параметры запроса
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/ds.DeleteEnrollmentToCourseRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
      summary: Удаляет связь курса с записью
      tags:
      - enrollments
  /enrollments:
    get:
      description: Возвращает список всех доступных записей
      parameters:
      - description: Статус записи
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Found
          schema:
            type: string
      summary: Получить записи
      tags:
      - Записи
  /login:
    post:
      consumes:
      - application/json
      description: Проверяет данные для входа и в случае успеха возвращает токен для
        входа
      parameters:
      - description: Данные для входа
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/app.loginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.loginResp'
      summary: Вход в систему
      tags:
      - Аутентификация
  /logout:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Выйти из системы
      tags:
      - Аутентификация
  /register:
    post:
      consumes:
      - application/json
      description: Добавляет в БД нового пользователя
      parameters:
      - description: Данные для регистрации
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/app.registerReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.registerResp'
      summary: Зарегистрировать нового пользователя
      tags:
      - Аутентификация
schemes:
- http
swagger: "2.0"
